## /*

Store.h

Authors: Destiny, Chengqi, Parisa

Main system class for the Movie Store.

Responsibilities:
• Load movie inventory from file
• Load customer records
• Process command file
• Handle borrow and return operations
• Display sorted inventory
• Display customer history

Inventory is stored in three separate containers
to maintain the required sorting order:

Comedy  -> sorted by title then year
Drama   -> sorted by director then title
Classic -> sorted by release date then actor
--------------------------------------------

*/

#ifndef STORE_H
#define STORE_H

#include <vector>
#include <map>
#include <string>

#include "Comedy.h"
#include "Drama.h"
#include "Classic.h"
#include "Customer.h"

using namespace std;

class Store {

private:

```
/*
------------------------------------------------------------
Movie inventory containers

Each movie type is stored in its own map to maintain
the required sorting order.

key = unique identifier generated by each movie class
value = pointer to movie object
------------------------------------------------------------
*/

map<string, Comedy*> comedyMovies;
map<string, Drama*> dramaMovies;
map<string, Classic*> classicMovies;


/*
------------------------------------------------------------
Customer database

key   = customer ID
value = pointer to Customer object
------------------------------------------------------------
*/

map<int, Customer*> customers;
```

public:

```
/*
------------------------------------------------------------
Destructor

Frees all dynamically allocated memory created by Store.
Implemented in Store.cpp.
------------------------------------------------------------
*/
~Store();


/*
------------------------------------------------------------
loadCustomers()

Reads customer records from file and stores them
in the customers map.
------------------------------------------------------------
*/
void loadCustomers(string filename);


/*
------------------------------------------------------------
loadMovies()

Reads movie inventory file and creates movie objects
using the appropriate movie subclass.
------------------------------------------------------------
*/
void loadMovies(string filename);


/*
------------------------------------------------------------
processCommands()

Reads the command file and executes each command.

Supported commands:
B -> Borrow movie
R -> Return movie
I -> Display inventory
H -> Display customer history
------------------------------------------------------------
*/
void processCommands(string filename);


/*
------------------------------------------------------------
showInventory()

Displays all movies in the store inventory
in the required order:

Comedy -> Drama -> Classic
------------------------------------------------------------
*/
void showInventory();


/*
------------------------------------------------------------
showHistory()

Displays the transaction history for a customer.
------------------------------------------------------------
*/
void showHistory(int id);


/*
------------------------------------------------------------
borrowMovie()

Processes a borrow transaction for a movie.
------------------------------------------------------------
*/
void borrowMovie(int id, char type, string key);


/*
------------------------------------------------------------
returnMovie()

Processes a return transaction for a movie.
------------------------------------------------------------
*/
void returnMovie(int id, char type, string key);
```

};

#endif
